#!/bin/bash

declare shost="schemaserver_test"
declare srmfile="$1"

declare -a comyad=(
    --title "wget result"
    --height 600
    --width 800
    )

declare -a comopts=(
    -q                      # quiet mode
    # -S                      # print server response headers
    -O -                    # output to stdout
    --header "Host: $shost" # spoof the hostname
)
declare -a options pdata yadopts
declare xmlresult

get_srm_database()
{
    echo "SchemaServer_Test"
}


confirm_proc_exists()
{
    local proc_name="$1"
    local -i pcount=0
    local query="\
SELECT COUNT(*)
  FROM ROUTINES \
 WHERE ROUTINE_SCHEMA='${DBNAME}' \
   AND ROUTINE_NAME='${proc_name}'"
 
    pcount=$( mysql -Ns information_schema -e "${query}" )

    # Ending with test "returns" the test result:
    [ $pcount -ne 0 ]
}

confirm_referenced_procedures()
{
    declare DBNAME=$( get_srm_database )
    local -i missing=0

    echo "Testing database '$DBNAME' for SRM-references procdures." >&2

    local -a procs_array
    procs_array=( $( awk -F ":" '/schema-proc|procedure/ { print $2 }' "$srmfile" | sort -u - ) )

    echo "About to check for the following procedures:"
    printf "'%s'\n" "${procs_array[@]}"

    local proc
    for proc in "${procs_array[@]}"; do
        if ! confirm_proc_exists "$proc"; then
            (( missing++ ))
            echo "Procedure '$proc' is missing."
        fi
    done

    if [ $missing -eq 0 ]; then
        echo "No references procedures are missing."
    else
        echo "There are $missing missing procedures."
    fi

    return $missing
}


show_default_page()
{
    local -a options yadopts
    local xmlresult
    options=( "http://localhost/${srmfile}" "${comopts[@]}" )
    xmlresult=$( wget "${options[@]}" )
    yadopts=( "${comyad[@]}" $( echo "${xmlresult}" | xsltproc test.xsl - ) )
    yad "${yadopts[@]}"
}

show_add_item_page()
{
    local -a options yadopts pdata
    local xmlresult
    options=( "http://localhost/${srmfile}?add" "${comopts[@]}" )
    pdata=( "add" )
    xmlresult=$( wget "${options[@]}" --post-data="${pdata[*]}" )
    echo "${xmlresult}"
    local IFS=$'\n'
    yadopts=( "${comyad[@]}" $( echo "${xmlresult}" | xsltproc test.xsl - ) )
    echo "${yadopts[@]}"
    yad "${yadopts[@]}"
}


confirm_referenced_procedures
if [ $? -ne 0 ]; then
    echo "Terminating test."
    exit 1
fi

show_add_item_page
show_default_page


# echo
# pdata=( "list" )
# echo "Get default page (a list page)"

# # echo "Get add form parameters:"
# options=( "http://localhost/Person.srm?add" "${comopts[@]}" )

# pdata=( "add" )
# xmlresult=$( wget "${options[@]}" --post-data="${pdata[*]}" )
# echo "${xmlresult}" | xsltproc test.xsl -


# echo "Add a person record"

# pdata=("fname=Chuck"
#        "lname=Jungmann"
#        "dob=1960-04-21" )

# options=( "http://localhost/Person.srm?add_submit" "${comopts[@]}" )
# xmlresult=$( wget "${options[@]}" --post-data="${pdata[*]}" )
# echo "${xmlresult}" | xsltproc test.xsl -

# options=( "http://localhost/Person.srm" "${comopts[@]}" )
# xmlresult=$( wget "${options[@]}" )
# echo "${xmlresult}" | xsltproc test.xsl -
